# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import processing.upload_path


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0019_auto_20160519_1940'),
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.BackType', verbose_name='\u0421\u043f\u0438\u043d\u043a\u0430')),
                ('hem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.HemType', verbose_name='\u041d\u0438\u0437')),
            ],
            options={
                'verbose_name': '\u0418\u0441\u0445\u043e\u0434\u043d\u0438\u043a \u0434\u043b\u044f \u0441\u043f\u0438\u043d\u043a\u0438',
                'verbose_name_plural': '\u0418\u0441\u0445\u043e\u0434\u043d\u0438\u043a\u0438 \u0434\u043b\u044f \u0441\u043f\u0438\u043d\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='BodySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionaries.CuffType', verbose_name='\u041c\u0430\u043d\u0436\u0435\u0442')),
                ('hem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.HemType', verbose_name='\u041d\u0438\u0437')),
                ('sleeve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.SleeveType', verbose_name='\u0420\u0443\u043a\u0430\u0432')),
            ],
            options={
                'verbose_name': '\u0418\u0441\u0445\u043e\u0434\u043d\u0438\u043a \u0434\u043b\u044f \u043e\u0441\u043d\u043e\u0432\u044b',
                'verbose_name_plural': '\u0418\u0441\u0445\u043e\u0434\u043d\u0438\u043a\u0438 \u0434\u043b\u044f \u043e\u0441\u043d\u043e\u0432\u044b',
            },
        ),
        migrations.CreateModel(
            name='CollarSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.CollarType', verbose_name='\u0412\u043e\u0440\u043e\u0442\u043d\u0438\u043a')),
            ],
            options={
                'verbose_name': '\u0418\u0441\u0445\u043e\u0434\u043d\u0438\u043a \u0434\u043b\u044f \u0432\u043e\u0440\u043e\u0442\u043d\u0438\u043a\u0430',
                'verbose_name_plural': '\u0418\u0441\u0445\u043e\u0434\u043d\u0438\u043a\u0438 \u0434\u043b\u044f \u0432\u043e\u0440\u043e\u0442\u043d\u0438\u043a\u0430',
            },
        ),
        migrations.CreateModel(
            name='ComposeSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uv', models.FileField(upload_to=processing.upload_path.UploadComposingSource(b'%s/uv/%s'), verbose_name='UV')),
                ('ao', models.FileField(upload_to=processing.upload_path.UploadComposingSource(b'%s/ao/%s'), verbose_name='\u0422\u0435\u043d\u0438')),
                ('light', models.FileField(upload_to=processing.upload_path.UploadComposingSource(b'%s/light/%s'), verbose_name='\u0421\u0432\u0435\u0442')),
                ('projection', models.CharField(choices=[(b'front', '\u041f\u0435\u0440\u0435\u0434\u043d\u044f\u044f'), (b'side', '\u0411\u043e\u043a\u043e\u0432\u0430\u044f'), (b'back', '\u0417\u0430\u0434\u043d\u044f\u044f')], max_length=5, verbose_name='\u041f\u0440\u043e\u0435\u043a\u0446\u0438\u044f')),
                ('back_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.BackSource')),
                ('body_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.BodySource')),
                ('collar_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.CollarSource')),
            ],
            options={
                'verbose_name': '\u041c\u043e\u0434\u0435\u043b\u044c \u0441\u0431\u043e\u0440\u043a\u0438',
                'verbose_name_plural': '\u041c\u043e\u0434\u0435\u043b\u0438 \u0441\u0431\u043e\u0440\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='CuffSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.CuffType', verbose_name='\u0422\u0438\u043f \u043c\u0430\u043d\u0436\u0435\u0442\u044b')),
                ('rounding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionaries.CuffRounding', verbose_name='\u0422\u0438\u043f \u0437\u0430\u043a\u0440\u0443\u0433\u043b\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0418\u0441\u0445\u043e\u0434\u043d\u0438\u043a \u0434\u043b\u044f \u043c\u0430\u043d\u0436\u0435\u0442',
                'verbose_name_plural': '\u0418\u0441\u0445\u043e\u0434\u043d\u0438\u043a\u0438 \u0434\u043b\u044f \u043c\u0430\u043d\u0436\u0435\u0442',
            },
        ),
        migrations.CreateModel(
            name='PlacketSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.PlacketType', verbose_name='\u0422\u0438\u043f \u043f\u043e\u043b\u043e\u0447\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u0418\u0441\u0445\u043e\u0434\u043d\u0438\u043a \u0434\u043b\u044f \u043f\u043e\u043b\u043e\u0447\u043a\u0438',
                'verbose_name_plural': '\u0418\u0441\u0445\u043e\u0434\u043d\u0438\u043a\u0438 \u0434\u043b\u044f \u043f\u043e\u043b\u043e\u0447\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='PocketSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dictionaries.PocketType', verbose_name='\u0422\u0438\u043f \u043a\u0430\u0440\u043c\u0430\u043d\u0430')),
            ],
            options={
                'verbose_name': '\u0418\u0441\u0445\u043e\u0434\u043d\u0438\u043a \u0434\u043b\u044f \u043a\u0430\u0440\u043c\u0430\u043d\u0430',
                'verbose_name_plural': '\u0418\u0441\u0445\u043e\u0434\u043d\u0438\u043a\u0438 \u0434\u043b\u044f \u043a\u0430\u0440\u043c\u0430\u043d\u0430',
            },
        ),
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture', models.ImageField(upload_to=b'', verbose_name='\u0424\u0430\u0439\u043b \u0442\u0435\u043a\u0441\u0442\u0443\u0440\u044b')),
                ('tiling', models.PositiveIntegerField(choices=[(4, '\u0421\u0442\u0430\u043d\u0434\u0430\u0440\u0442\u043d\u044b\u0439'), (8, '\u0423\u0447\u0430\u0449\u0435\u043d\u043d\u044b\u0439 (\u04452)')], default=4, verbose_name='\u0422\u0430\u0439\u043b\u0438\u043d\u0433')),
                ('needs_shadow', models.BooleanField(default=True, verbose_name='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u0442\u0435\u043d\u0438')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043a\u0441\u0442\u0443\u0440\u0430',
                'verbose_name_plural': '\u0422\u0435\u043a\u0441\u0442\u0443\u0440\u044b',
            },
        ),
        migrations.DeleteModel(
            name='ComposingSource',
        ),
        migrations.AddField(
            model_name='composesource',
            name='cuff_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.CuffSource'),
        ),
        migrations.AddField(
            model_name='composesource',
            name='placket_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.PlacketSource'),
        ),
        migrations.AddField(
            model_name='composesource',
            name='pocket_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.PocketSource'),
        ),
        migrations.AlterUniqueTogether(
            name='cuffsource',
            unique_together=set([('cuff', 'rounding')]),
        ),
        migrations.AlterUniqueTogether(
            name='bodysource',
            unique_together=set([('sleeve', 'hem', 'cuff')]),
        ),
        migrations.AlterUniqueTogether(
            name='backsource',
            unique_together=set([('back', 'hem')]),
        ),
    ]
