# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_auto_20160605_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backsource',
            options={'verbose_name': '\u041a\u043e\u043d\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u044f \u0441\u0431\u043e\u0440\u043a\u0438 \u0434\u043b\u044f \u0441\u043f\u0438\u043d\u043a\u0438', 'verbose_name_plural': '\u041a\u043e\u043d\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u0438 \u0441\u0431\u043e\u0440\u043a\u0438 \u0434\u043b\u044f \u0441\u043f\u0438\u043d\u043a\u0438'},
        ),
        migrations.AlterModelOptions(
            name='bodysource',
            options={'verbose_name': '\u041a\u043e\u043d\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u044f \u0441\u0431\u043e\u0440\u043a\u0438 \u0434\u043b\u044f \u043e\u0441\u043d\u043e\u0432\u044b', 'verbose_name_plural': '\u041a\u043e\u043d\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u0438 \u0441\u0431\u043e\u0440\u043a\u0438 \u0434\u043b\u044f \u043e\u0441\u043d\u043e\u0432\u044b'},
        ),
        migrations.AlterModelOptions(
            name='collarsource',
            options={'verbose_name': '\u041a\u043e\u043d\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u044f \u0441\u0431\u043e\u0440\u043a\u0438 \u0434\u043b\u044f \u0432\u043e\u0440\u043e\u0442\u043d\u0438\u043a\u0430', 'verbose_name_plural': '\u041a\u043e\u043d\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u0438 \u0441\u0431\u043e\u0440\u043a\u0438 \u0434\u043b\u044f \u0432\u043e\u0440\u043e\u0442\u043d\u0438\u043a\u0430'},
        ),
        migrations.AlterModelOptions(
            name='cuffsource',
            options={'verbose_name': '\u041a\u043e\u043d\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u044f \u0441\u0431\u043e\u0440\u043a\u0438 \u0434\u043b\u044f \u043c\u0430\u043d\u0436\u0435\u0442', 'verbose_name_plural': '\u041a\u043e\u043d\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u0438 \u0441\u0431\u043e\u0440\u043a\u0438 \u0434\u043b\u044f \u043c\u0430\u043d\u0436\u0435\u0442'},
        ),
        migrations.AlterModelOptions(
            name='placketsource',
            options={'verbose_name': '\u041a\u043e\u043d\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u044f \u0441\u0431\u043e\u0440\u043a\u0438 \u0434\u043b\u044f \u043f\u043e\u043b\u043e\u0447\u043a\u0438', 'verbose_name_plural': '\u041a\u043e\u043d\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u0438 \u0441\u0431\u043e\u0440\u043a\u0438 \u0434\u043b\u044f \u043f\u043e\u043b\u043e\u0447\u043a\u0438'},
        ),
        migrations.AlterModelOptions(
            name='pocketsource',
            options={'verbose_name': '\u041a\u043e\u043d\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u044f \u0441\u0431\u043e\u0440\u043a\u0438 \u0434\u043b\u044f \u043a\u0430\u0440\u043c\u0430\u043d\u0430', 'verbose_name_plural': '\u041a\u043e\u043d\u0444\u0438\u0433\u0443\u0440\u0430\u0446\u0438\u0438 \u0441\u0431\u043e\u0440\u043a\u0438 \u0434\u043b\u044f \u043a\u0430\u0440\u043c\u0430\u043d\u0430'},
        ),
        migrations.AddField(
            model_name='backsource',
            name='tuck',
            field=models.BooleanField(choices=[(False, '\u0411\u0435\u0437 \u0432\u044b\u0442\u0430\u0447\u0435\u043a'), (True, '\u0421 \u0432\u044b\u0442\u0430\u0447\u043a\u0430\u043c\u0438')], default=False, verbose_name='\u0412\u044b\u0442\u0430\u0447\u043a\u0438'),
        ),
        migrations.AlterUniqueTogether(
            name='backsource',
            unique_together=set([('back', 'hem', 'tuck')]),
        ),
    ]
