# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_auto_20160610_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttonssource',
            name='body_buttons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.BodyButtonsSource'),
        ),
        migrations.AddField(
            model_name='buttonssource',
            name='collar_buttons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.CollarButtonsSource'),
        ),
        migrations.AddField(
            model_name='buttonssource',
            name='cuff_buttons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.CuffButtonsSource'),
        ),
    ]
