# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-11 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_auto_20160610_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backsource',
            name='tuck',
            field=models.BooleanField(choices=[(False, '\u0411\u0435\u0437 \u0432\u044b\u0442\u0430\u0447\u043a\u0438'), (True, '\u0421 \u0432\u044b\u0442\u0430\u0447\u043a\u0430\u043c\u0438')], default=False, verbose_name='\u0412\u044b\u0442\u0430\u0447\u043a\u0438'),
        ),
    ]
