# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20160204_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomShirt',
            fields=[
            ],
            options={
                'verbose_name': '\u0420\u0443\u0431\u0430\u0448\u043a\u0430',
                'proxy': True,
                'verbose_name_plural': '\u0420\u0443\u0431\u0430\u0448\u043a\u0438',
            },
            bases=('backend.shirt',),
        ),
        migrations.CreateModel(
            name='TemplateShirt',
            fields=[
            ],
            options={
                'verbose_name': '\u0428\u0430\u0431\u043b\u043e\u043d \u0440\u0443\u0431\u0430\u0448\u043a\u0430',
                'proxy': True,
                'verbose_name_plural': '\u0428\u0430\u0431\u043b\u043e\u043d\u044b \u0440\u0443\u0431\u0430\u0448\u0435\u043a',
            },
            bases=('backend.shirt',),
        ),
        migrations.AlterModelOptions(
            name='shirt',
            options={},
        ),
        migrations.AddField(
            model_name='shirt',
            name='code',
            field=models.CharField(max_length=255, null=True, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='meterial',
            field=models.CharField(default='', max_length=255, verbose_name='\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shirt',
            name='showcase_image',
            field=models.ImageField(null=True, upload_to=b'', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0432\u0438\u0442\u0440\u0438\u043d\u044b'),
        ),
    ]
