# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20160216_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shirt',
            old_name='meterial',
            new_name='material',
        ),
    ]
