# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20160216_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirtimage',
            name='shirt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirt_images', to='backend.Shirt'),
        ),
    ]
