# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20160216_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='showcase_image',
            field=models.ImageField(null=True, upload_to=b'showcase', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0432\u0438\u0442\u0440\u0438\u043d\u044b'),
        ),
        migrations.AlterField(
            model_name='shirtimage',
            name='image',
            field=models.ImageField(upload_to=b'showcase', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
