# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20160216_2301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contrastdetails',
            unique_together=set([('shirt', 'element')]),
        ),
    ]
