# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20160302_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storehouse',
            old_name='title',
            new_name='country',
        ),
    ]
