# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20160302_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shirts', to='backend.Collection', verbose_name='\u041a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u044f'),
        ),
    ]
