# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20160303_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='sex',
            field=models.CharField(choices=[(b'male', '\u041c\u0443\u0436\u0441\u043a\u043e\u0439'), (b'female', '\u0416\u0435\u043d\u0441\u043a\u0438\u0439'), (b'unisex', '\u0423\u043d\u0438\u0441\u0435\u043a\u0441')], default=b'male', max_length=6, verbose_name='\u041f\u043e\u043b'),
        ),
    ]
