# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 12:02
from __future__ import unicode_literals

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_collection_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='price',
            field=models.DecimalField(decimal_places=2, editable=backend.models.Fabric, max_digits=10, null=True, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
