# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_shirt_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirt',
            name='material',
        ),
        migrations.AddField(
            model_name='fabric',
            name='material',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
