# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('backend', '0024_auto_20160312_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.IntegerField(blank=True, max_length=255, null=True, verbose_name='object ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u0426\u0435\u043d\u0430')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories_price', to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'verbose_name': '\u0426\u0435\u043d\u0430 \u043d\u0430\u0434\u0431\u0430\u0432\u043a\u0438',
                'verbose_name_plural': '\u0426\u0435\u043d\u044b \u043d\u0430\u0434\u0431\u0430\u0432\u043e\u043a',
            },
        ),
        migrations.AlterUniqueTogether(
            name='accessoriesprice',
            unique_together=set([('content_type', 'object_pk')]),
        ),
    ]
