# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0013_auto_20160229_2312'),
        ('backend', '0024_auto_20160312_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custombuttons',
            options={'ordering': ('type',), 'verbose_name': '\u041a\u0430\u0441\u0442\u043e\u043c\u043d\u044b\u0435 \u043f\u0443\u0433\u043e\u0432\u0438\u0446\u044b', 'verbose_name_plural': '\u041a\u0430\u0441\u0442\u043e\u043c\u043d\u044b\u0435 \u043f\u0443\u0433\u043e\u0432\u0438\u0446\u044b'},
        ),
        migrations.AddField(
            model_name='shirt',
            name='custom_buttons_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionaries.CustomButtonsType', verbose_name='\u0422\u0438\u043f \u043a\u0430\u0441\u0442\u043e\u043c\u043d\u044b\u0445 \u043f\u0443\u0433\u043e\u0432\u0438\u0446'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='clasp',
            field=models.BooleanField(choices=[(False, '\u041d\u0435 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u0437\u0430\u0441\u0442\u0435\u0436\u043a\u0443'), (True, '\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u0437\u0430\u0441\u0442\u0435\u0436\u043a\u0443')], default=False, verbose_name='\u0417\u0430\u0441\u0442\u0435\u0436\u043a\u0430 \u043f\u043e\u0434 \u0448\u0442\u0438\u0444\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='custom_buttons',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field=b'custom_buttons_type', chained_model_field=b'type', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.CustomButtons', verbose_name='\u041a\u0430\u0441\u0442\u043e\u043c\u043d\u044b\u0435 \u043f\u0443\u0433\u043e\u0432\u0438\u0446\u044b'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='tuck',
            field=models.BooleanField(choices=[(False, '\u0411\u0435\u0437 \u0432\u044b\u0442\u0430\u0447\u0435\u043a'), (True, '\u0421 \u0432\u044b\u0442\u0430\u0447\u043a\u0430\u043c\u0438')], default=False, verbose_name='\u0412\u044b\u0442\u0430\u0447\u043a\u0438'),
        ),
    ]
