# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20160315_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('collections', models.ManyToManyField(related_name='hardness', to='backend.Collection', verbose_name='\u041a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u0438')),
            ],
            options={
                'verbose_name': '\u0416\u0435\u0441\u0442\u043a\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u0416\u0435\u0441\u0442\u043a\u043e\u0441\u0442\u044c',
            },
        ),
        migrations.AlterModelOptions(
            name='custombuttons',
            options={'verbose_name': '\u041a\u0430\u0441\u0442\u043e\u043c\u043d\u044b\u0435 \u043f\u0443\u0433\u043e\u0432\u0438\u0446\u044b', 'verbose_name_plural': '\u041a\u0430\u0441\u0442\u043e\u043c\u043d\u044b\u0435 \u043f\u0443\u0433\u043e\u0432\u0438\u0446\u044b'},
        ),
        migrations.RemoveField(
            model_name='collar',
            name='hardness',
        ),
        migrations.RemoveField(
            model_name='cuff',
            name='hardness',
        ),
    ]
