# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20160315_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='collar',
            name='hardness',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Hardness', verbose_name='\u0416\u0435\u0441\u0442\u043a\u043e\u0441\u0442\u044c'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuff',
            name='hardness',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Hardness', verbose_name='\u0416\u0435\u0441\u0442\u043a\u043e\u0441\u0442\u044c'),
            preserve_default=False,
        ),
    ]
