# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20160315_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombuttons',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='dictionaries.CustomButtonsType', verbose_name='\u0422\u0438\u043f'),
        ),
    ]
