# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20160315_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('collections', models.ManyToManyField(related_name='stays', to='backend.Collection', verbose_name='\u041a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u0438')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u0441\u0442\u043e\u0447\u043a\u0438',
                'verbose_name_plural': '\u041a\u043e\u0441\u0442\u043e\u0447\u043a\u0438',
            },
        ),
        migrations.RemoveField(
            model_name='collar',
            name='stays',
        ),
        migrations.AddField(
            model_name='collar',
            name='stays',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Stays', verbose_name='\u041a\u043e\u0441\u0442\u043e\u0447\u043a\u0438'),
        ),
    ]
