# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20160315_2247'),
        ('backend', '0025_auto_20160315_0656'),
    ]

    operations = [
    ]
