# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20160317_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='tailoring_time',
            field=models.CharField(max_length=255, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043f\u043e\u0448\u0438\u0432\u0430 \u0438 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438'),
        ),
    ]
