# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoriesprice',
            name='object_pk',
            field=models.IntegerField(blank=True, null=True, verbose_name='object ID'),
        ),
        migrations.AlterField(
            model_name='contrastdetails',
            name='shirt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirt_contrast_details', to='backend.Shirt', verbose_name='\u0420\u0443\u0431\u0430\u0448\u043a\u0430'),
        ),
    ]
