# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20160316_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='custom_buttons_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_shirts', to='dictionaries.CustomButtonsType', verbose_name='\u0422\u0438\u043f \u043a\u0430\u0441\u0442\u043e\u043c\u043d\u044b\u0445 \u043f\u0443\u0433\u043e\u0432\u0438\u0446'),
        ),
    ]
