# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20160317_1031'),
        ('backend', '0028_auto_20160319_0813'),
        ('backend', '0030_auto_20160317_0917'),
    ]

    operations = [
    ]
