# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_collection_tailoring_time'),
        ('backend', '0031_merge'),
    ]

    operations = [
    ]
