# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_auto_20160321_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
