# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_auto_20160321_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesprice',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='accessories_prices', to='backend.Collection', verbose_name='\u041a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u0438'),
        ),
    ]
