# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0014_auto_20160402_1404'),
        ('backend', '0036_auto_20160324_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initials',
            name='font',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionaries.Font', verbose_name='\u0428\u0440\u0438\u0444\u0442'),
        ),
    ]
