# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_auto_20160324_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricresidual',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='\u041e\u0441\u0442\u0430\u0442\u043e\u043a'),
        ),
    ]
