# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_auto_20160402_1412'),
        ('backend', '0038_auto_20160331_0419'),
    ]

    operations = [
    ]
