# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='description',
            field=models.TextField(null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
