# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_auto_20160404_1407'),
        ('backend', '0040_fabric_fabric_type'),
    ]

    operations = [
    ]
