# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_fabric_fabric_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardShirt',
            fields=[
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u043d\u0434\u0430\u0440\u0442\u043d\u044b\u0439 \u0432\u0430\u0440\u0438\u0430\u043d\u0442 \u0440\u0443\u0431\u0430\u0448\u043a\u0438',
                'proxy': True,
                'verbose_name_plural': '\u0421\u0442\u0430\u043d\u0434\u0430\u0440\u0442\u043d\u044b\u0435 \u0432\u0430\u0440\u0438\u0430\u043d\u0442\u044b \u0440\u0443\u0431\u0430\u0448\u0435\u043a',
            },
            bases=('backend.shirt',),
        ),
        migrations.AddField(
            model_name='shirt',
            name='is_standard',
            field=models.BooleanField(default=False, editable=False, verbose_name='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0435\u0442\u0441\u044f \u043a\u0430\u043a \u0441\u0442\u0430\u043d\u0434\u0430\u0440\u0442\u043d\u044b\u0439 \u0432\u0430\u0440\u0438\u0430\u043d\u0442'),
        ),
    ]
