# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_fabric_fabric_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='shawl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ShawlOptions', verbose_name='\u041f\u043b\u0430\u0442\u043e\u043a'),
        ),
    ]
