# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabric',
            options={'ordering': ('code',), 'verbose_name': '\u0422\u043a\u0430\u043d\u044c', 'verbose_name_plural': '\u0422\u043a\u0430\u043d\u0438'},
        ),
    ]
