# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_auto_20160408_0852'),
        ('backend', '0042_auto_20160407_0955'),
    ]

    operations = [
    ]
