# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='long_description',
            field=models.TextField(blank=True, null=True, verbose_name='\u0414\u043b\u0438\u043d\u043d\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
