# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='fabric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Fabric', verbose_name='\u0422\u043a\u0430\u043d\u044c'),
        ),
    ]
