# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='dickey',
            field=models.BooleanField(default=False, verbose_name='\u041c\u0430\u043d\u0438\u0448\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='dickey',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dickey_list', to='backend.Fabric'),
        ),
    ]
