# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='active',
            field=models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u0430'),
        ),
    ]
