# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_auto_20160423_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='dickey',
            field=models.BooleanField(default=False, verbose_name='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0435\u0442\u0441\u044f \u0432 \u043c\u0430\u043d\u0438\u0448\u043a\u0435'),
        ),
    ]
