# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_auto_20160423_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirt',
            name='description',
        ),
    ]
