# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_remove_shirt_description'),
        ('backend', '0045_auto_20160423_1518'),
        ('backend', '0044_fabric_active'),
        ('backend', '0044_fabric_thickness'),
    ]

    operations = [
    ]
