# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_auto_20160423_1518'),
        ('backend', '0047_auto_20160427_0817'),
    ]

    operations = [
    ]
