# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-15 07:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_auto_20160504_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999)], verbose_name='\u0418\u043d\u0434\u0435\u043a\u0441')),
                ('city', models.CharField(max_length=255, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('street', models.CharField(max_length=255, verbose_name='\u0423\u043b\u0438\u0446\u0430')),
                ('home', models.CharField(max_length=255, verbose_name='\u0414\u043e\u043c')),
            ],
            options={
                'verbose_name': '\u041c\u0430\u0433\u0430\u0437\u0438\u043d',
                'verbose_name_plural': '\u041c\u0430\u0433\u0430\u0437\u0438\u043d\u044b',
            },
        ),
    ]
