# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-21 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_auto_20160514_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrastdetails',
            name='element',
            field=models.CharField(choices=[(b'collar', '\u0412\u043e\u0440\u043e\u0442\u043d\u0438\u043a'), (b'collar_face', '\u0412\u043e\u0440\u043e\u0442\u043d\u0438\u043a \u043b\u0438\u0446\u0435\u0432\u0430\u044f \u0441\u0442\u043e\u0440\u043e\u043d\u0430'), (b'collar_bottom', '\u0412\u043e\u0440\u043e\u0442\u043d\u0438\u043a \u043d\u0438\u0437'), (b'collar_outer', '\u0412\u043e\u0440\u043e\u0442\u043d\u0438\u043a \u0432\u043d\u0435\u0448\u043d\u044f\u044f \u0441\u0442\u043e\u0439\u043a\u0430'), (b'collar_inner', '\u0412\u043e\u0440\u043e\u0442\u043d\u0438\u043a \u0432\u043d\u0443\u0442\u0440\u0435\u043d\u043d\u044f \u0441\u0442\u043e\u0439\u043a\u0430'), (b'cuff', '\u041c\u0430\u043d\u0436\u0435\u0442\u0430'), (b'cuff_outer', '\u041c\u0430\u043d\u0436\u0435\u0442\u0430 \u0432\u043d\u0435\u0448\u043d\u044f\u044f'), (b'cuff_inner', '\u041c\u0430\u043d\u0436\u0435\u0442\u0430 \u0432\u043d\u0443\u0442\u0440\u0435\u043d\u043d\u044f')], max_length=20, verbose_name='\u042d\u043b\u0435\u043c\u0435\u043d\u0442'),
        ),
        migrations.AlterField(
            model_name='contraststitch',
            name='shirt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrast_stitches', to='backend.Shirt'),
        ),
    ]
