# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-15 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
