# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-05 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_auto_20160428_0436'),
        ('backend', '0049_auto_20160504_0737'),
    ]

    operations = [
    ]
