# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-21 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_auto_20160521_1915'),
        ('backend', '0051_merge'),
    ]

    operations = [
    ]
