# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_auto_20160612_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='sex',
            field=models.CharField(choices=[(b'male', '\u041c\u0443\u0436\u0441\u043a\u0430\u044f'), (b'female', '\u0416\u0435\u043d\u0441\u043a\u0430\u044f'), (b'unisex', '\u0423\u043d\u0438\u0441\u0435\u043a\u0441')], default=b'male', max_length=6, verbose_name='\u041f\u043e\u043b \u043a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='long_description',
            field=models.TextField(blank=True, default=b'', verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='material',
            field=models.CharField(default=b'', max_length=255, verbose_name='\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='short_description',
            field=models.TextField(blank=True, default=b'', verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
