# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_auto_20160616_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='texture',
        ),
    ]
