# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-15 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_certificate_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='value',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c'),
        ),
    ]
