# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-11 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20160515_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='id',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='\u0423\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440 \u0441\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u0430'),
        ),
    ]
