# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-11 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20160611_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='index',
            field=models.IntegerField(verbose_name='\u0418\u043d\u0434\u0435\u043a\u0441'),
        ),
    ]
