# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20160611_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('customer', models.OneToOneField(max_length=255, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='checkout.Customer', to_field=b'number', verbose_name='\u0423\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f')),
                ('discount_value', models.FloatField(default=0, null=True, verbose_name='\u041f\u0440\u043e\u0446\u0435\u043d\u0442 \u0441\u043a\u0438\u0434\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u0421\u043a\u0438\u0434\u043a\u0430',
                'verbose_name_plural': '\u0421\u043a\u0438\u0434\u043a\u0438',
            },
        ),
    ]
