# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20160623_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0437\u0430\u043a\u0430\u0437\u0430'),
        ),
    ]
