# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20160623_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.Shop', to_field=b'index', verbose_name='\u041c\u0430\u0433\u0430\u0437\u0438\u043d'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.Customer', to_field=b'number', verbose_name='\u041a\u043b\u0438\u0435\u043d\u0442'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='checkout.Order', verbose_name='\u0417\u0430\u043a\u0430\u0437'),
        ),
    ]
