# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0012_auto_20160204_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='collarbuttons',
            name='types',
            field=models.ManyToManyField(blank=True, to='dictionaries.CollarType', verbose_name='\u0422\u0438\u043f\u044b \u0432\u043e\u0440\u043e\u0442\u043d\u0438\u043a\u043e\u0432'),
        ),
        migrations.AddField(
            model_name='cuffrounding',
            name='types',
            field=models.ManyToManyField(blank=True, to='dictionaries.CuffType', verbose_name='\u0422\u0438\u043f\u044b'),
        ),
    ]
