# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0013_auto_20160229_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('font', models.FileField(upload_to=b'fonts', verbose_name='\u0424\u0430\u0439\u043b \u0448\u0440\u0438\u0444\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u0428\u0440\u0438\u0444\u0442 (\u0434\u043b\u044f \u0438\u043d\u0438\u0446\u0438\u0430\u043b\u043e\u0432)',
                'verbose_name_plural': '\u0428\u0440\u0438\u0444\u0442\u044b (\u0434\u043b\u044f \u0438\u043d\u0438\u0446\u0438\u0430\u043b\u043e\u0432)',
            },
        ),
        migrations.AddField(
            model_name='color',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
