# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0014_auto_20160402_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabriccolor',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
