# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0014_auto_20160402_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='\u0422\u0438\u043f')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0442\u043a\u0430\u043d\u0438',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0442\u043a\u0430\u043d\u0435\u0439',
            },
        ),
    ]
