# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0015_auto_20160404_1407'),
        ('dictionaries', '0015_fabrictype'),
    ]

    operations = [
    ]
