# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0016_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thickness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0422\u043e\u043b\u0449\u0438\u043d\u0430 \u0442\u043a\u0430\u043d\u0438',
                'verbose_name_plural': '\u0422\u043e\u043b\u0449\u0438\u043d\u0430 \u0442\u043a\u0430\u043d\u0438',
            },
        ),
    ]
