# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0018_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u044f'),
        ),
    ]
